
SchemaVersion: '1.0'
SageMaker:
  PythonSDK:
    Modules:
      TelemetryOptOut: true
      RemoteFunction:
        # role arn is not required if in SageMaker Notebook instance or SageMaker Studio
        # Uncomment the following line and replace with the right execution role if in a local IDE
        # RoleArn: <replace the role arn here>
        # image_uri: <replace with your image URI>
        InstanceType: ml.m5.xlarge
        EnvironmentVariables: {'MLFLOW_TRACKING_URI': arn:aws:sagemaker:us-west-2:975049911976:mlflow-tracking-server/mlflow-d-vuu8gn51m6ef, 'LOGNAME': sagemakeruser, 'MLFLOW_EXPERIMENT_NAME': sm-pipeline-experiment, 'AWS_REGION': us-west-2}
        Dependencies: ./requirements.txt
        IncludeLocalWorkDir: True
        CustomFileFilter:
          IgnoreNamePatterns:
          - "data/*"
          - "models/*"
          - "*.ipynb"
          - "__pycache__"


